feat: clean up and simplify logging functions and add support for printing classes
MSUTeam/MSU pull request #147
Opened 2022-05-25 22:58 UTC by Enduriel

2022-05-26 06:19 UTC, TaroEld reviewed
Please use format when concatenating more than 2 strings

2022-05-26 06:19 UTC, TaroEld commented on scripts/config/msu/log.nut
> +				string += key + " = " + this.getLocalString(value, _maxLen, _maxDepth, _advanced, false) + ", ";
Use format()

2022-05-26 06:19 UTC, TaroEld commented on scripts/config/msu/log.nut
> +		if (["array", "table"].find(typeof _data) != null  && _data.len() > _maxLenMin)
I prefer `if (typeof _data == ("array" || "table"))`

2022-05-26 06:19 UTC, TaroEld commented on scripts/config/msu/log.nut
> +				ret += key + " = " + this.getLocalString(value, _maxLen, _depth - 1, _advanced, _printClasses) + ", ";
Use format()

2022-05-26 06:19 UTC, TaroEld commented on scripts/config/msu/log.nut
> +				ret += key + " = " + this.getLocalString(_value[key], _maxLen, _depth - 1, _advanced, _printClasses) + ", ";
Use format()

2022-05-26 06:19 UTC, TaroEld commented on scripts/config/msu/log.nut
> +			ret += "\"" + _value + "\"";
Use format()

2022-06-06 18:00 UTC, LordMidas requested changes

2022-06-07 05:50 UTC, Enduriel commented on scripts/config/msu/log.nut
> +		else if (typeof _value == "table" && _value.len() <= _maxLen && _depth > 0) // full table
This was originally a switch as you can see, it's not actually cleaner and makes it a lot more difficult to parse, a chain of else ifs makes it a little annoying, but is MUCH better than the alternative.

2022-06-07 05:51 UTC, Enduriel commented on scripts/config/msu/log.nut
> +		else if (["instance", "class"].find(typeof _value) != null && _depth > 0 && _printClasses) // full instance or class
Refer to the other discussion

2022-06-07 21:06 UTC, Enduriel commented
after discussion midas was okay with it as is

2022-06-07 21:06 UTC, merged