feat: add tooltip string coloring functions to MSU.String
MSUTeam/MSU pull request #151
Opened 2022-06-02 01:52 UTC by Enduriel

2022-06-02 15:43 UTC, LordMidas requested changes
1. In my opinion these should be in MSU.Text namespace but I won't die on that hill.
2. Add a function called `::MSU.String.addNewColor( _name, _value )` that allows modders to create new colors in the ::Const.Color table. This is useful for example in PTR where I use a similar system to create colors for coding Passive, Active and One-Time Effect perk headings.
3. I would remove the colorBlue function as it is not used in any vanilla thing afaik. If it is, then keep it. Otherwise, only keep the colorGreen and colorRed. For other colors, modders can use the color( function.

2022-06-02 16:53 UTC, LordMidas requested changes

2022-06-02 16:53 UTC, LordMidas commented on scripts/config/msu/string.nut
> +	function color( _string, _color )
the argument order should take _color first and then _string as it will look cleaner in code with longer strings.

2022-06-07 19:47 UTC, TaroEld approved these changes
lgtm

2022-07-25 15:09 UTC, merged