feat: add onEquip and onUnquip events for skills
MSUTeam/MSU pull request #163
Opened 2022-07-01 23:22 UTC by LordMidas

The explicit Boolean check (ret == true) is because the vanilla unequip function can return null as well

2022-07-02 10:25 UTC, TaroEld approved these changes
LGTM

2022-07-25 07:42 UTC, Enduriel commented on msu/hooks/items/item_container.nut
> +	}
onUnequip should be called before the item is unequipped (this is how items handle it). This requires us to redo some checks from item container first, but isn't actually that bad.

2022-07-25 07:42 UTC, Enduriel requested changes

2022-07-25 07:42 UTC, Enduriel commented on msu/hooks/items/item_container.nut
> +		return ret;
onUnequip should be called before the item is unequipped (this is how items handle it). This requires us to redo some checks from item container first, but isn't actually that bad.

2022-07-25 08:28 UTC, Enduriel approved these changes

2022-07-25 08:55 UTC, merged