fix: include files in config/msu as early as possible
MSUTeam/MSU pull request #176
Opened 2022-07-28 12:28 UTC by LordMidas

2022-07-28 22:00 UTC, Enduriel approved these changes
I mean sure

2022-07-30 19:54 UTC, TaroEld approved these changes
lgtm assuming you tried it and there isn't some whacky load order issue

2022-08-11 19:19 UTC, LordMidas commented on scripts/config/!msu.nut
> +::includeLoad <- function( _prefix, _folder )
Perhaps these functions should be in `::MSU.` namespace?

2022-08-11 19:19 UTC, LordMidas commented on scripts/config/!msu.nut
> +::includeFiles(::IO.enumerateFiles("scripts/config/msu"));
As we have `!msu.nut` in the `scripts/config` folder, perhaps it is best to move the Classes etc. that we moved to that folder for the idea of "loading them before hooks" back to the `/msu` folder and instead use this method to load them early i.e. during config load?

2022-08-12 09:42 UTC, Enduriel approved these changes
Sure, I actually like it better this way as well

2022-08-20 08:50 UTC, Enduriel requested changes
After the moves of ::includeFile, ::includeFiles and ::includeLoad, I think this has moved outside the scope of the initial PR, and I'd want some more discussion on whether these moves are really for the best.

2022-10-31 03:45 UTC, LordMidas commented
This PR will be merged when all other PRs for this release have been merged - due to the folder structure change. Any other files/changes that were added in other PRs that need to be moved will be moved and added to this PR at that time.

2022-11-18 03:20 UTC, LordMidas commented
Reminder for self: Also move `msu/config` to `msu/hooks/config`

2022-12-22 13:36 UTC, Enduriel approved these changes

2022-12-22 15:42 UTC, TaroEld approved these changes

2022-12-22 15:55 UTC, merged