feat: add addBehavior utility function
MSUTeam/MSU pull request #203
Opened 2022-09-12 18:07 UTC by LordMidas

Allows writing stuff like:
```squirrel
addBehavior("BFAttackLunge", "Attack.BF_Lunge", 50, 100);
```
Instead of:
```squirrel
::Const.AI.Behavior.ID.BFAttackLunge <- id;
::Const.AI.Behavior.Name.push("Attack.BF_Lunge");
::Const.AI.Behavior.ID.COUNT = id + 1;
::Const.AI.Behavior.Order.BFAttackLunge <- 50;
::Const.AI.Behavior.Score.BFAttackLunge <- 100;
```

2022-09-23 17:58 UTC, TaroEld commented
The latter probably

2022-10-22 11:57 UTC, Enduriel requested changes
`::MSU.AI` is better imo

2022-10-29 08:51 UTC, LordMidas commented
I will move these to an `MSU.AI` namespace and merge it after #176 has been merged.

2022-10-29 17:32 UTC, TaroEld requested changes

2022-10-29 17:32 UTC, TaroEld commented on msu/config/ai.nut
> +	::Const.AI.Behavior.Score.BFAttackLunge <- _score;
Should be 
```
::Const.AI.Behavior.Order[_id] <- _order;
::Const.AI.Behavior.Scorer[_id] <- _score;
```

2022-10-30 17:40 UTC, merged