feat: add modsetting that supresses the basegame keybinds so that onl…
MSUTeam/MSU pull request #251
Opened 2022-12-05 09:06 UTC by TaroEld

…y the MSU system is used
The point is to be able to properly unbind and rebind keys, without the base keybinds still being active.

2022-12-06 18:06 UTC, LordMidas requested changes
The correct spelling is "Suppress" with a double p. Please correct throughout the PR in variable names and description tooltip. 

On a side note, perhaps we should change the name of the "Vanilla" panel in keybinds to "Vanilla (MSU)" to make it clear that these are the MSU keybinds for vanilla. I have recently seen a user for whom this wasn't clear.

2022-12-10 16:25 UTC, LordMidas approved these changes
Minor if you feel like changing now:
Better wording for tooltip: "Whether base keybinds should be suppressed. This means that only the MSU system will be used for keybinds.\nFor example, if you set 'Open Character Screen' from 'c' to 'tab' then without this setting, pressing 'c' will still open the character screen. With this setting, only 'tab' will open it.");

2022-12-12 22:04 UTC, Enduriel commented
With the caveat that I assume the ID will get capitalized in another PR

2022-12-12 23:22 UTC, TaroEld commented
> 

No reason I can't do it in this one

2022-12-12 23:23 UTC, merged