fix: flagSerialization edge case errors
MSUTeam/MSU pull request #280
Opened 2023-01-25 16:59 UTC by Enduriel

serialization of BB objects is now handled by passing a Serialization or Deserialization Emulator to them.

Normal deserialiation now requires a default value.

SerDeEmulators are now permanently linked to a FlagContainer they are assigned during instantiation.

SerializationEmulators now have an Incremental mode where they store their data in the flag container as soon as something is written to them.

DeserializationEmulators now immediately clear flags from their FlagContainer as they deserialize.

SerDeEmulator flag IDs are validated to make sure they do not collide with flags generated by other emulators.

2023-01-26 16:22 UTC, TaroEld approved these changes

2023-01-26 16:22 UTC, TaroEld commented on msu/systems/mod_settings/abstract_setting.nut
> +			this.__setFromSerializationTable(this.getMod().Serialization.flagDeserialize(format("MS.%s", this.getID()), this.__getSerializationTable()));
I'd prefer if we defined the format string either the line before or via a separate function so this line becomes more readable

2023-01-26 16:22 UTC, TaroEld commented on msu/systems/serialization/deserialization_emulator.nut
> +	// }
We talked about removing this until there's a need for it

2023-01-26 21:17 UTC, LordMidas requested changes
@Enduriel When you have time please explain to me the EmulatorsToClear and Incremental thingies.

2023-01-29 22:04 UTC, TaroEld approved these changes

2023-02-08 20:04 UTC, LordMidas approved these changes
Please replace `MS.` with `ModSetting.` and then we're good to go.

2023-02-08 21:28 UTC, merged