fix: handling for adding/removing weapontype during hooks
MSUTeam/MSU pull request #369
Opened 2024-06-10 09:45 UTC by Enduriel

2024-06-10 18:08 UTC, TaroEld approved these changes
works for me

2024-06-11 04:35 UTC, LordMidas requested changes

2024-06-11 04:35 UTC, LordMidas commented on msu/hooks/items/weapons/weapon.nut
> +		this.setupWeaponType(false);
I don't think this works. Example:
- A vanilla weapon that does `this.m.Categories = "Axe"` in its `create()`.
- Mod A hooks this function, calls the `__original()` and does `addWeaponType(Spear)`.
- This goes to `setupWeaponType(false)` which sets the WeaponType to `None`. Then goes through all the categories, sets it to `Axe`. Then the `addWeaponType` function set it to `Axe | Spear`. Note that the Categories are not updated/set here.
- Mod B hooks afterward and says `addWeaponType(Hammer)`.
- This goes to `setupWeaponType(false)` which sets the WeaponType to `None`. Then goes through all the categories, sets it to `Axe`. Then the `addWeaponType` function set it to `Axe | Hammer`. Note that this means that the `Spear` added by Mod A is lost.

I guess the solution is to also set up the categories immediately after `setupWeaponType` in `addWeaponType` and `removeWeaponType`.

2024-06-11 04:35 UTC, LordMidas commented on msu/hooks/items/weapons/weapon.nut
I don't think the Boolean is necessary. We can simply always update both the weapontype and categories before adding/removing weapontypes. I've pushed a commit that you can check.

2024-06-11 04:40 UTC, LordMidas commented on msu/hooks/items/weapons/weapon.nut
Ah, I guess one problem there is that currently we allow adding weapon types without updating categories `_setupCategories = true` by default which can be passed as `false`. So "technically" it allows someone to add a weapon type to a weapon but not list that in the categories. Although this probably shouldn't be allowed - I don't remember why I added that Boolean param, maybe it was for performance reasons if someone wants to add/remove several weapon types from a weapon they don't update categories every single time. But in hindsight this seems like an unnecessary performance optimization and allows a certain design choice which is bad and shouldn't be allowed i.e. weapon types added without showing in categories.

In any case, the thing is that the new approach will no longer allow that design choice to work because will always ensure that every weapon type shows up in the categories. Are we ok with this side-effect?

2024-06-11 05:41 UTC, LordMidas approved these changes

2024-06-11 05:41 UTC, merged