feat: print current day to log when loading campaign
MSUTeam/MSU pull request #385
Opened 2024-07-05 20:26 UTC by LordMidas

2024-07-05 20:31 UTC, Enduriel requested changes

2024-07-05 20:46 UTC, TaroEld commented on msu/hooks/states/world_state.nut
> +		::logInfo(::World.getTime().Days);
Yeah, also who's saying this (msu)

2024-07-05 20:47 UTC, LordMidas commented on msu/hooks/states/world_state.nut
> +		::logInfo(::World.getTime().Days);
Yeah makes sense. I don't know why I'm printing just an integer - I just blanked out completely on this lol. Will fix.

2024-07-06 09:41 UTC, Enduriel approved these changes

2024-07-06 14:29 UTC, TaroEld approved these changes

2024-07-06 18:06 UTC, merged