Improve error message in addEvent()
MSUTeam/MSU pull request #424
Opened 2024-09-23 06:06 UTC by Suor

2024-09-23 06:53 UTC, TaroEld approved these changes

2024-09-24 07:37 UTC, LordMidas requested changes
The changes look good. The commit message needs to be changed to follow conventional commits guidelines. So it could be something like: `refactor: improve error message for defparams in addEvent`

2024-09-24 08:02 UTC, TaroEld commented
Can't you just do that on merge?

2024-09-24 08:03 UTC, LordMidas commented
> Can't you just do that on merge?

Ah yes. I can do that during `Squash and Merge` yes.

2024-09-24 08:04 UTC, LordMidas approved these changes

2024-09-28 12:51 UTC, merged