feat: add new onHired and onOtherPlayerHired events for skills
MSUTeam/MSU pull request #434
Opened 2024-10-06 18:42 UTC by Darxo

`onHired` is an event already present in Vanilla but only in the `player.nut` and for origins.
Skills however can't react to the hiring of someone.

### This PR proposes two new events for skills:
```
// This event is triggered once for every skill of a player character directly after the onHired event of that player class is triggered
function onHired()

// This event is triggered once for every skill of every other character in the player roster after the onHired event of a player class is triggered
function onOtherPlayerHired( _otherCharacter )
```

## Possible Use Cases
### onHired
- Certain backgrounds can apply mood buff/debuff on hiring, depending on what other backgrounds are already present in the player party
- Some traits might act as a wildcard/unrevelaed at first (despite trying out) and only transform into a real trait after hiring

### onOtherPlayerHired
- Certain backgrounds might cause a brother to get a positive/negative mood when you hire a certain background
- Certain backgrounds/perks could grant a bonus to every new recruit (e.g. free perk/stats)

2025-02-14 14:15 UTC, TaroEld approved these changes
LGTM

2025-02-14 15:14 UTC, Enduriel approved these changes

2025-02-14 15:18 UTC, LordMidas requested changes

2025-02-14 15:18 UTC, LordMidas commented on msu/hooks/entity/tactical/player.nut
> +	}
Note that starting characters in an origin do not call this `player.onHired()` function. So, should these events be called for those characters?

2025-02-14 15:18 UTC, LordMidas commented on msu/hooks/skills/skill.nut
> +	}
Two points:
- Would it be a better setup is to simply have a single event `onHired( _bro )` or `onAnyBroHired( _bro )`? Then for the case of the bro himself you pass him, and for others you pass the other actor.
- The word `Player` in the function name `onOtherPlayerHired` seems awkward as it has other connotations besides the `player.nut` class. So maybe something like `onOtherBroHired` is better. Other suggestions?

2025-02-14 15:18 UTC, LordMidas commented on msu/hooks/skills/skill_container.nut
> +// New Events
This `// New Events` comment is completely out of place here as there are many new events even above this. So I'd just remove this single line.

2025-02-14 15:18 UTC, LordMidas commented on msu/hooks/skills/skill.nut
> +// New Events
Same comment about this `// New Events` line.

2025-02-16 07:04 UTC, Darxo commented on msu/hooks/entity/tactical/player.nut
> +	}
For non-random scenarios it is up to the scenario designer to manually implement interactions that his starting brothers might have.
For this implementation im purely leeching onto the vanilla onHired function and keeping within its juristiction

2025-02-16 07:11 UTC, Darxo commented on msu/hooks/skills/skill.nut
> +	}
I switched to the single event

2025-02-16 18:14 UTC, TaroEld approved these changes
LGTM after typo fixes / name change.

2025-02-16 18:14 UTC, TaroEld commented on msu/hooks/entity/tactical/player.nut
> +			bro.getSkills().onAnyoneHired(this);
onAnyoneHired here, onAnyBroHired later.
Personally I also think that onBroHired is good enough.

2025-02-16 18:14 UTC, TaroEld commented on msu/hooks/skills/skill.nut
> +	/// @param _bro is a refernce to the player object whose onHired event was triggered
refernce -> reference

2025-02-28 20:37 UTC, Darxo commented on msu/hooks/entity/tactical/player.nut
> +			bro.getSkills().onAnyoneHired(this);
I removed the left-over `onAnyBroHired` here.
If you prefer another term over `onAnyBroHired` you gotta convince midas

2025-03-11 06:30 UTC, LordMidas approved these changes

2025-03-11 06:34 UTC, LordMidas commented on msu/hooks/entity/tactical/player.nut
> +	}
Ok, I think we can do it like this. If there are concerns in the future we can resolve them at that time.

2025-03-11 06:35 UTC, merged